### ISSUE TITLE
I can't get Google Plus to show

### ISSUE THREAD

**Issue by Oak-Trees** [Julienh/Sharrre#35]
I have the Twitter and Facebook buttons up on the site, but the Google Plus just doesn't want to show. I use the sharrre.php file, I tried multiple locations, I'm pretty sure the javascript finds the php file.

When I link it to the sharrre.php on the sharrre.com site, it works!

Might this be a setting my web host uses? And than of course, my question would be check setting.

**Comment by vomLeben** [comment]
I have had the same issue. The Test returned a message similar to the one that EgonS posted. So i contactet my hoster. 

It turned out that the curloption "CURLOPT_FOLLOWLOCATION => true" within the sharrre.php caused a redirect from the given relative path to the absolute one. Because of open_basedir (which my hoster wasn't able to change for me), this new absolute path was blocked. Switching this optin to false solved my problem.

Google+ button is now shown correctly.

Hope this helps!
